# fly.toml file generated for chatbot-telegram on 2023-01-30T14:25:35+05:30

app = "chatbot-telegram"
kill_signal = "SIGINT"
kill_timeout = 5

[env]

[experimental]
  auto_rollback = false

[[services]]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[deploy]
  release_command = "pkill -9 node"
